name: build-site

on:
  push:
    branches: [ source ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: cnerg/cnerg.github.io-deps

    steps:
      - uses: actions/checkout@v2

      - name: build the site
        run: |
          ls -al
#          make docker-gh-stage,
#          make docker-gh-push